# Generated by Django 5.1.7 on 2025-03-12 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatgroup_message_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar_style',
            field=models.CharField(default='avataaars', max_length=50),
        ),
    ]
