# Generated by Django 5.1.7 on 2025-03-12 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_remove_profile_avatar_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgroup',
            name='group_picture',
            field=models.ImageField(default='group_pics/default_group.jpg', upload_to='group_pics'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='profile_pics/default_user.png', upload_to='profile_pics'),
        ),
    ]
